repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: pytest-check
        name: PyTest Runner
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true